training:
  initial_lr: 0.001
  epochs: 50
  pretrain_steps: 10000
  horizon_update_steps: 1000
  batch_size: 32
  shuffle: true
  num_workers: 4

model:
  input_channels: 3
  additional_2d_channels: 2
  latent_dim: 128

data: